services:
  nginx:
    image: ghcr.io/fttranscendenceorganization/ft_nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/ssl/netpong:/etc/ssl:ro
      - ../nginx/conf.d/default.conf:/etc/nginx/templates/default.conf.template:ro
    env_file:
      - /etc/netpong/nginx.env
    networks:
      - public_net
      - internal_net
    depends_on:
      - backend_api
      - front_end
    restart: always

  front_end:
    image: ghcr.io/fttranscendenceorganization/ft_frontend:latest
    networks:
      - internal_net
    restart: always

  backend_api:
    image: ghcr.io/fttranscendenceorganization/ft_backend:latest
    env_file:
      - /etc/netpong/backend.env
    networks:
      - internal_net
    depends_on:
      database:
        condition: service_healthy
    restart: always


  database:
    image: postgres:17
    env_file:
      - /etc/netpong/database.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db_data:

networks:
  public_net:
    driver: bridge
    name: public_net
  internal_net:
    driver: bridge
    name: internal_net
